// sub-app/vue3-ts-app/src/components/ChangeMicroAppButton.vue
<template>
  <div class="row">
    <button @click="changeRoute">跳到react app 微应用</button>
  </div>
</template>

<script lang="ts" setup>
import { inject } from "vue";

const $shared = inject("$shared") as any;

function changeRoute() {
  $shared.dispatch({
    type: "CHANGE_ROUTE",
    payload: "/app-react/index",
  });
}
</script>

<style lang="scss" scoped>
.row {
  margin: 8px;
  text-align: center;
}
</style>

// sub-app/react-ts-app/src/components/ChangeMicroAppButton/index.tsx
import { useShared } from '@/context/SharedContext';
import { FC } from 'react';
import styles from './index.module.scss';

const ChangeRouteButton: FC = () => {
  const shared = useShared();

  const changeRoute = () => {
    shared?.dispatch({
      type: 'CHANGE_ROUTE',
      payload: '/app-vue/index',
    });
  };

  return (
    <div className={styles['button-row']}>
      <button onClick={changeRoute}>跳转到vue app 微应用</button>
    </div>
  );
};

export default ChangeRouteButton;
