// sub-app/react-ts-app/src/pages/404.tsx
// import { useShared } from '@/context/SharedContext';
// import { useEffect } from 'react';

function Page404() {
  // const shared = useShared();

  // useEffect(() => {
  //   if (window.__POWERED_BY_QIANKUN__) {
  //     shared!.dispatch({
  //       type: 'CHANGE_ROUTE',
  //       payload: '/404',
  //     });
  //   }
  // }, [shared]);

  return <div style={{ marginTop: '20vh', fontSize: '18px', textAlign: 'center' }}>404</div>;
}

export default Page404;

// sub-app/vue-app/src/views/404.vue
<template>
  <div class="container">404</div>
</template>

<script>
export default {
  name: "404-page",
  beforeCreate() {
    if (window.__POWERED_BY_QIANKUN__) {
      this.$shared.dispatch({
        type: "CHANGE_ROUTE",
        payload: "/404",
      });
    }
  },
};
</script>

<style lang="scss" scoped>
.container {
  text-align: center;
  margin-top: 20vh;
  font-size: 18px;
}
</style>
