// sub-app/vue-app/src/components/ChangeRoute.vue
<template>
  <div>
    <div class="change-route-buttons">
      <router-link class="button" :to="{ name: 'page-a' }">PageA</router-link>
      <router-link class="button" :to="{ name: 'page-b' }">PageB</router-link>
      <router-link class="button" :to="{ name: 'page-main' }">主页</router-link>
    </div>
    <router-view></router-view>
  </div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
.change-route-buttons {
  text-align: center;

  .button {
    margin: 12px;
  }
}
</style>

// sub-app/react-ts-app/src/components/ChangeRoute/index.tsx
import React, { FC } from "react";
import { Link,  useRoutes, Outlet } from "react-router-dom";
import './index.scss'


export const routes = [
    {
        path:'/',
        element: <div>MainPage</div>,
    },
    {
        path:'/page-a',
        element: (<div>
                    PageA
                    <div className="change-route-buttons">
                        <Link className="button" to="/page-a/a-1">A1</Link>
                        <Link className="button" to="/page-a/a-2">A2</Link>
                        <Outlet/>
                    </div>
                </div>),
        meta: {title: 'PageA'},
        children:[
            {
                path: 'a-1',
                meta: {title: 'A1'},
                element: <div>A1</div>
            },
            {
                path: 'a-2',
                meta: {title: 'A2'},
                element: <div>A2</div>
            },
        ]
    },
    {
        path:'/page-b',
        element: <div>PageB</div>,
        meta: {title: 'PageB'},
    }
]

const ChangeRoute: FC = ()=>{

    const element = useRoutes(routes)
    
    return (
        <div>
            <div className="change-route-buttons">
                <Link className="button" to="/page-a">PageA</Link>
                <Link className="button" to="/page-b">PageB</Link>
                <Link className="button" to="/">MainPage</Link>
            </div>
            {element}
        </div>
    )
}

export default ChangeRoute;
