// sub-app/react-ts-app/src/components/ChangeMicroAppButton/index.tsx

import { FC } from 'react';
import styles from './index.module.scss';

const ChangeRouteButton: FC = () => {

  const changeRoute = () => {
    window.dispatchEvent(new CustomEvent('micro-app-dispatch',{
      detail:{
        type: 'CHANGE_ROUTE',
        payload: '/app-vue/index',
      }
    }))
  };

  return (
    <div className={styles['button-row']}>
      <button onClick={changeRoute}>跳转到vue app 微应用</button>
    </div>
  );
};

export default ChangeRouteButton;

// sub-app/vue-app/src/components/ChangeMicroAppButton.vue
<template>
  <div class="row">
    <button @click="changeRoute">跳到react app 微应用</button>
  </div>
</template>

<script>
export default {
  methods: {
    changeRoute() {
      window.dispatchEvent(new CustomEvent('micro-app-dispatch',{
        detail:{
          type: "CHANGE_ROUTE",
          payload: "/app-react/index",
        }
      }))
    },
  },
};
</script>

<style lang="scss" scoped>
.row {
  margin: 8px;
  text-align: center;
}
</style>
