// sub-app/react-ts-app/src/components/ThemeColor/index.tsx
import { FC } from 'react';
import { useSelector } from 'react-redux';
import { RootState } from '@/store';
import './index.scss';

const ThemeColor: FC = () => {
  const theme = useSelector<RootState, RootState['app']['theme']>((state) => state.app.theme);

  return (
    <div className="tips">
      当前主题色：
      <div className="color-well" style={{ background: `${theme}` }} />
    </div>
  );
};

export default ThemeColor;

// sub-app/vue-app/src/components/ThemeColor.vue
<template>
    <div class="tips">
        当前主题色：
        <div class="color-well" :style="{background: `${theme}`}"/>
    </div>
</template>

<script>
import {mapState} from 'vuex'

export default {
    computed:{
        ...mapState({
            theme: state=>state.app.theme
        })
    }
}
</script>

<style lang="scss" scoped>
    .tips{
        text-align: center;

        .color-well{
            display: inline-block;
            width: 200px;
            height: 1.5em;
            vertical-align: bottom;
            border-radius: 4px;
        }
    }
</style>
