// sub-app/vue-app/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <ThemeColor/>
    <ChangeMicroAppButton/>
    <ChangeRoute/>
  </div>
</template>

<script>
import ThemeColor from '@/components/ThemeColor'
import ChangeMicroAppButton from '@/components/ChangeMicroAppButton'
import ChangeRoute from '@/components/ChangeRoute'

export default {
  name: 'App',
  components:{
    ThemeColor,
    ChangeMicroAppButton,
    ChangeRoute
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// sub-app/react-ts-app/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';
import ThemeColor from '@/components/ThemeColor';
import ChangeMicroAppButton from './components/ChangeMicroAppButton';
import ChangeRoute from './components/ChangeRoute';


function App() {

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <ThemeColor />
        <ChangeMicroAppButton/>
        <ChangeRoute/>
      </header>
    </div>
  );
}

export default App;
